version: "3.8"
services:
  postgres:
    container_name: postgres-task2db
    image: postgres:15.3-bookworm
    environment:
      POSTGRES_DB: "tasks2db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/pgserver:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d tasks1db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  pgadmin:
    container_name: pgadmin-task2db
    image: dpage/pgadmin4:7.3
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "gureev_e@1cps.ru"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "8085:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  zookeeper:
    container_name: zookeeper-task2db
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    ports:
      - 22181:2181
    volumes:
      - ./volumes/zookeeper/.data:/var/lib/zookeeper/data
      - ./volumes/zookeeper/.log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 3185

  kafka:
    container_name: kafka-task2db
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9095:9095
    restart: unless-stopped
    volumes:
      - ./volumes/kafka/.data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:3185"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui-task2db
    image: provectuslabs/kafka-ui:latest
    ports:
      - 3085:8080
    restart: unless-stopped
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: dev_cluster1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
